POST http://localhost:4600/notes
Content-Type: application/json

{
    "title": "Eat",
    "content": "go for a pizza",
    "createdAt": "2023-04-04"
} 
###get all notes
GET http://localhost:4600/notes


### get one note
GET http://localhost:4600/notes/2868f63e-727f-4d8b-a74a-be10d18d4f42

###update a note
PUT http://localhost:4600/notes/2868f63e-727f-4d8b-a74a-be10d18d4f42
Content-Type: application/json


{
    "title": "EatEAS",
    "content": "go for a pizzaEAS",
    "createdAt": "2023-04-04"
}

###delete a note
DELETE http://localhost:4600/notes/2868f63e-727f-4d8b-a74a-be10d18d4f42